 - name: Install AD-Domain-Services feature
   win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
 
 - name: Setup Active Directory Controller
   win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ safe_mode_password }}"
   register: active_directory_controllers

 - name: Reboot Server after AD Installation
   win_reboot: 
   when: active_directory_controllers.reboot_required

 - name: List Domain Names
   win_shell: nltest /dclist:"{{ ad_domain_name }}"
   register: domain_list

 - debug:
     var: domain_list
